# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# Forcing py==3.12 since Sphinx extension epub3 requires imghdr removed in 3.13
version: 2
sphinx:
  configuration: doc/source/conf.py
python:
  install:
    - requirements: envs/requirements-doc.txt
submodules:
  recursive: false
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
